package net.mamoe.mirai.deps.test

/**
 * This file was generated by Gradle task `generateBuildConfig`.
 */
object BuildConfig {
    /**
     * Kotlin version used to compile mirai-core
     */
    const val kotlinVersion = "1.7.0"
}
